"""create initial database schema

Revision ID: a153db291edf
Revises: 
Create Date: 2026-08-22 09:25:34.761545+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a153db291edf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('address_raw', sa.Text(), nullable=False, comment='Оригинальный адрес, как пришёл из источника'),
    sa.Column('address_normalized', sa.Text(), nullable=True, comment='Нормализованный адрес после геокодирования; используется как первичный ключ идентичности здания при поиске дублей'),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('year_built', sa.SmallInteger(), nullable=True),
    sa.Column('floors_total', sa.SmallInteger(), nullable=True),
    sa.Column('building_type', sa.String(length=20), nullable=True, comment='Тип дома: panel, brick, monolith, other. CHECK constraint — Decision Checklist п.6.'),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Координаты здания (PostGIS geography, WGS84). ST_DWithin и ST_Distance работают в метрах. Порядок: ST_MakePoint(longitude, latitude).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buildings_city', 'buildings', ['city'], unique=False)
    op.create_index('ix_buildings_location', 'buildings', ['location'], unique=False, postgresql_using='gist')
    op.create_table('search_requests',
    sa.Column('address_raw', sa.Text(), nullable=False, comment='Адрес в виде, введённом пользователем'),
    sa.Column('address_normalized', sa.Text(), nullable=True, comment='Нормализованный адрес после геокодирования'),
    sa.Column('lat', sa.Double(), nullable=True, comment='Широта, результат геокодирования (DOUBLE PRECISION)'),
    sa.Column('lon', sa.Double(), nullable=True, comment='Долгота (DOUBLE PRECISION)'),
    sa.Column('rooms', sa.SmallInteger(), nullable=False, comment='Количество комнат (0 = студия)'),
    sa.Column('area', sa.Numeric(precision=8, scale=2), nullable=False, comment='Площадь, м²'),
    sa.Column('floor', sa.SmallInteger(), nullable=True, comment='Этаж'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='Прочие параметры запроса (расширяемость)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Используется Celery для определения «недавних» локаций'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_requests_created_at', 'search_requests', [sa.text('created_at DESC')], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Человекочитаемое имя источника (уникальное)'),
    sa.Column('base_url', sa.Text(), nullable=True, comment='Базовый URL сайта-источника'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Флаг активности; неактивные источники не опрашиваются'),
    sa.Column('adapter_class', sa.String(length=200), nullable=False, comment='Python fully-qualified class name адаптера'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='Конфигурация, специфичная для адаптера (timeout, headers и т.п.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_sources_name')
    )
    op.create_index('ix_sources_is_active', 'sources', ['is_active'], unique=False)
    op.create_table('properties',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor', sa.SmallInteger(), nullable=True, comment='Этаж квартиры'),
    sa.Column('rooms', sa.SmallInteger(), nullable=False, comment='Количество комнат; 0 = студия'),
    sa.Column('area_total', sa.Numeric(precision=8, scale=2), nullable=False, comment='Общая площадь, м²'),
    sa.Column('area_living', sa.Numeric(precision=8, scale=2), nullable=True, comment='Жилая площадь, м²'),
    sa.Column('area_kitchen', sa.Numeric(precision=8, scale=2), nullable=True, comment='Площадь кухни, м²'),
    sa.Column('is_studio', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Явный флаг студии (дублирует rooms = 0 для читаемости)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_properties_building_id', 'properties', ['building_id'], unique=False)
    op.create_index('ix_properties_rooms_area_total', 'properties', ['rooms', 'area_total'], unique=False)
    op.create_table('raw_listings',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False, comment='Идентификатор объявления в системе источника'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Полный оригинальный payload от источника (неизменяем после записи)'),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время сбора данных'),
    sa.Column('is_processed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг: нормализовано ли объявление в listings'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_raw_listings_source_external')
    )
    op.create_index('ix_raw_listings_processed_collected', 'raw_listings', ['is_processed', 'collected_at'], unique=False)
    op.create_table('valuation_results',
    sa.Column('search_request_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False, comment="Версия алгоритма оценки, напр. 'v1.0'. Обязательна для аудита и различения результатов разных версий логики."),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Параметры конкретного запуска оценки: radius_m, iqr_multiplier, max_comparables, веса компонентов и другие влияющие настройки. Позволяет воспроизвести расчёт независимо от текущих env-переменных.'),
    sa.Column('median_asking_price', sa.BigInteger(), nullable=False, comment='Медианная цена по comparables, kopecks'),
    sa.Column('mean_asking_price', sa.BigInteger(), nullable=False, comment='Средняя цена, kopecks'),
    sa.Column('min_asking_price', sa.BigInteger(), nullable=False, comment='Минимальная цена, kopecks (вторичная статистика)'),
    sa.Column('max_asking_price', sa.BigInteger(), nullable=False, comment='Максимальная цена, kopecks (вторичная статистика)'),
    sa.Column('p25_asking_price', sa.BigInteger(), nullable=False, comment='25-й перцентиль, kopecks (нижняя граница диапазона)'),
    sa.Column('p75_asking_price', sa.BigInteger(), nullable=False, comment='75-й перцентиль, kopecks (верхняя граница диапазона)'),
    sa.Column('median_price_per_sqm', sa.BigInteger(), nullable=False, comment='Медианная цена за м², kopecks'),
    sa.Column('mean_price_per_sqm', sa.BigInteger(), nullable=False, comment='Средняя цена за м², kopecks'),
    sa.Column('weighted_asking_price', sa.BigInteger(), nullable=False, comment='Основная оценка: weighted_median_price_per_sqm × area, kopecks'),
    sa.Column('confidence_score', sa.Double(), nullable=False, comment='Внутренний score 0.0–1.0; в UI отображается как цветовой badge'),
    sa.Column('comparables_count', sa.Integer(), nullable=False, comment='Количество использованных объявлений (после IQR-фильтра)'),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Момент вычисления оценки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['search_request_id'], ['search_requests.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_valuation_results_computed_at', 'valuation_results', [sa.text('computed_at DESC')], unique=False)
    op.create_index('ix_valuation_results_search_request_id', 'valuation_results', ['search_request_id'], unique=False)
    op.create_table('listings',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False, comment='ID объявления в системе источника'),
    sa.Column('url', sa.Text(), nullable=True, comment='Прямая ссылка на объявление'),
    sa.Column('asking_price', sa.BigInteger(), nullable=False, comment='Запрашиваемая цена, kopecks. Цена продавца, не подтверждённая сделка.'),
    sa.Column('asking_price_per_sqm', sa.BigInteger(), nullable=False, comment='Цена за м², kopecks. = asking_price / area_total, вычисляется при нормализации (ROUND_HALF_UP).'),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'active'"), nullable=False, comment='Состояние объявления: active, sold, removed. CHECK constraint — Decision Checklist п.6 (открыт).'),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата публикации объявления (по данным источника)'),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата снятия объявления (NULL, если ещё активно)'),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Координаты объявления (PostGIS geography, WGS84). Может отличаться от buildings.location. Порядок: ST_MakePoint(longitude, latitude).'),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True, comment='FK → listings.id; указывает на каноническое объявление. NULL = не дубликат.'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='Дополнительные атрибуты, специфичные для источника'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['listings.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_listings_source_external')
    )
    op.create_index('ix_listings_duplicate_of_id_notnull', 'listings', ['duplicate_of_id'], unique=False, postgresql_where=sa.text('duplicate_of_id IS NOT NULL'))
    op.create_index('ix_listings_listed_at', 'listings', ['listed_at'], unique=False)
    op.create_index('ix_listings_location_active', 'listings', ['location'], unique=False, postgresql_using='gist', postgresql_where=sa.text("duplicate_of_id IS NULL AND status = 'active'"))
    op.create_index('ix_listings_property_id', 'listings', ['property_id'], unique=False)
    op.create_index('ix_listings_status', 'listings', ['status'], unique=False)
    op.create_table('listing_price_history',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('asking_price', sa.BigInteger(), nullable=False, comment='Зафиксированная цена в kopecks на момент записи'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время фиксации цены (момент обнаружения изменения коллектором)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_price_history_listing_recorded', 'listing_price_history', ['listing_id', sa.text('recorded_at DESC')], unique=False)
    op.create_table('valuation_comparables',
    sa.Column('valuation_result_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False, comment='FK → listings.id для audit/lineage; расчёт не зависит от текущего состояния строки listings'),
    sa.Column('rank', sa.Integer(), nullable=False, comment='Порядковый номер comparable в наборе, отсортированном по similarity_score DESC. Первый по схожести = 1.'),
    sa.Column('weight', sa.Double(), nullable=False, comment='Вес comparable в расчёте weighted_asking_price. Сумма весов по всему valuation_result_id = 1.0.'),
    sa.Column('similarity_score', sa.Double(), nullable=False, comment='Итоговый взвешенный score схожести, 0.0–1.0'),
    sa.Column('distance_m', sa.Double(), nullable=False, comment='Расстояние от comparable до объекта оценки, метры (geography ST_Distance). Компонент similarity_score и отображается пользователю.'),
    sa.Column('asking_price_snapshot', sa.BigInteger(), nullable=False, comment='listings.asking_price на момент оценки, kopecks'),
    sa.Column('asking_price_per_sqm_snapshot', sa.BigInteger(), nullable=False, comment='listings.asking_price_per_sqm на момент оценки, kopecks. Ключевое поле: IQR-фильтр и weighted median опираются на него.'),
    sa.Column('area_total_snapshot', sa.Numeric(precision=8, scale=2), nullable=False, comment='properties.area_total на момент оценки, м²'),
    sa.Column('rooms_snapshot', sa.SmallInteger(), nullable=False, comment='properties.rooms на момент оценки'),
    sa.Column('floor_snapshot', sa.SmallInteger(), nullable=True, comment='properties.floor на момент оценки; NULL если не указан'),
    sa.Column('building_type_snapshot', sa.String(length=20), nullable=True, comment='buildings.building_type на момент оценки; NULL если не определён'),
    sa.Column('source_id_snapshot', sa.UUID(), nullable=False, comment='listings.source_id на момент оценки. Идентифицирует происхождение comparable без JOIN.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['valuation_result_id'], ['valuation_results.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_valuation_comparables_listing_id', 'valuation_comparables', ['listing_id'], unique=False)
    op.create_index('ix_valuation_comparables_result_id', 'valuation_comparables', ['valuation_result_id'], unique=False)
    op.create_index('ix_valuation_comparables_result_rank', 'valuation_comparables', ['valuation_result_id', 'rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_valuation_comparables_result_rank', table_name='valuation_comparables')
    op.drop_index('ix_valuation_comparables_result_id', table_name='valuation_comparables')
    op.drop_index('ix_valuation_comparables_listing_id', table_name='valuation_comparables')
    op.drop_table('valuation_comparables')
    op.drop_index('ix_listing_price_history_listing_recorded', table_name='listing_price_history')
    op.drop_table('listing_price_history')
    op.drop_index('ix_listings_status', table_name='listings')
    op.drop_index('ix_listings_property_id', table_name='listings')
    op.drop_index('ix_listings_location_active', table_name='listings', postgresql_using='gist', postgresql_where=sa.text("duplicate_of_id IS NULL AND status = 'active'"))
    op.drop_index('ix_listings_listed_at', table_name='listings')
    op.drop_index('ix_listings_duplicate_of_id_notnull', table_name='listings', postgresql_where=sa.text('duplicate_of_id IS NOT NULL'))
    op.drop_table('listings')
    op.drop_index('ix_valuation_results_search_request_id', table_name='valuation_results')
    op.drop_index('ix_valuation_results_computed_at', table_name='valuation_results')
    op.drop_table('valuation_results')
    op.drop_index('ix_raw_listings_processed_collected', table_name='raw_listings')
    op.drop_table('raw_listings')
    op.drop_index('ix_properties_rooms_area_total', table_name='properties')
    op.drop_index('ix_properties_building_id', table_name='properties')
    op.drop_table('properties')
    op.drop_index('ix_sources_is_active', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_search_requests_created_at', table_name='search_requests')
    op.drop_table('search_requests')
    op.drop_index('ix_buildings_location', table_name='buildings', postgresql_using='gist')
    op.drop_index('ix_buildings_city', table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
